version: '3'
services:
  301-redirect:
    build: .
    command: "npm run dev"
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
      environment:
      NODE_ENV: 'development'
      VIRTUAL_HOST: "*.301.abbi-studio.local"
volumes: 
  node_modules: