version: '3'
services:
  301-redirect:
    image: abdalem/301-redirect
    environment:
      NODE_ENV: "production"
      VIRTUAL_PORT: "3000"
      VIRTUAL_HOST: "*.301.abbi-studio.fr"
networks:
  default:
    external:
      name: nginx-reverse-proxy